### ISSUE TITLE
Change equality of average hydro constraint

### ISSUE THREAD

**Issue by pesap** [RAEL-Berkeley/switch#114]
Change the <= by equality

## Code to replace
```python
    mod.Enforce_Hydro_Avg_Flow = Constraint(
         mod.HYDRO_GEN_TS,
         rule=lambda m, g, hts:
         enforce_hydro_avg_flow_scaling_factor *
         # Compute the weighted average of the dispatch
         sum(m.DispatchGen[g, t] * m.tp_weight[t] for t in m.TPS_IN_HTS[hts])
         / sum(m.tp_weight[tp] for tp in m.TPS_IN_HTS[hts])
         <= m.hydro_avg_flow_mw[g, hts] * enforce_hydro_avg_flow_scaling_factor
     )
```

**Comment by staadecker** [comment]
@pesap can you give some reasoning to why this is. I think I had made the change because my understanding is it's always possible to "curtail" generation (even hydro) however let me know if I'm wrong.

**Comment by pesap** [comment]
@staadecker,

From the discussion that we had with @jszinai and @PatyHidalgo, we agreed that it is better not to curtail the hydro plants because of the way the average hydros flows were calculated.

**Comment by staadecker** [comment]
Sounds good!
