### ISSUE TITLE
Change transmission line lifetime

### ISSUE THREAD

**Issue by staadecker** [RAEL-Berkeley/switch#80]
Transmission line lifetime is currently 20 years which is too low. We should increase this to a more reasonable value.

**Comment by pesap** [comment]
Hey @staadecker, see the table below for some reference that we can use to select an appropriate value.

We can keep adding to this table as we find more references.

Source | Lifetime in years
:-- | --
[Professor John Kassakian from MIT]( https://tinyurl.com/aej4ajcb) | ~100
[Xcel Energy factsheet](https://tinyurl.com/88vhv6yw) | 80+
[WIS:dom model](https://tinyurl.com/4km8ukpk) | 60
[UCS](https://www.ucsusa.org/sites/default/files/attach/gw-smart-infrastructure-table-life-expectancy.pdf) | 50
[PGE Transmission manual](https://tinyurl.com/2b3vpbjb) | 70+


cc @jszinai @PatyHidalgo

**Comment by staadecker** [comment]
My bet is that the industry values (Xcel and PGE) are more accurate than the research (UCS) or modelling values (WIS). Combined with the fact the transmission lines are often used well beyond their lifetime, I would lean for using 80 years. Thoughts?

**Comment by staadecker** [comment]
For reference purposes, in the end, we decided on an 85 year lifetime.
